- name: begin handler_test main role
  debug:
    msg: first task in handler_test main role
  notify: calling handler
  changed_when: true

- name: subrole1
  include_role:
    name: "{{ role_path }}/roles/subrole1"
  vars:
    __myvar: main1

- name: subrole2
  include_role:
    name: "{{ role_path }}/roles/subrole1"
  vars:
    __myvar: main2

- name: end handler_test main role
  debug:
    msg: last task in handler_test main role
  notify: calling handler
  changed_when: true
