---
- name: changed test
  hosts: localhost
  gather_facts: false
  tasks:
    - command: ls
      register: __ls_result

    - debug:
        msg: facts 2 {{ ansible_facts }}
      when: not __ls_result is changed
 
    - command: ls
      changed_when: false

    - debug:
        msg: facts 2 {{ ansible_facts }}

    - include_role:
        name: change_test
      register: change_test_role_result

    - debug:
        msg: result {{ change_test_role_result }}

