---
- name: test task 1
  hosts: localhost
  roles:
    - handler_test
  tasks:
    - name: first task in test
      debug:
        msg: first task in test
      notify: calling handler
      changed_when: true
    - name: include handler_test tasks
      include_tasks: roles/handler_test/tasks/main.yml
    - name: flush handlers
      meta: flush_handlers
    - name: last task in test
      debug:
        msg: last task in test
      notify: calling handler
      changed_when: true
