- hosts: all
  vars:
    kernel_settings_sysctl:
      - name: fs.epoll.max_user_watches
        value: 1048576
      - name: fs.file-max
        value: 16777216
    kernel_settings_sysfs:
      - name: /sys/class/net/lo/mtu
        value: 32767
    kernel_settings_systemd_cpu_affinity: "1,3,5,7"
    kernel_settings_transparent_hugepages: madvise
    kernel_settings_transparent_hugepages_defrag: defer
  roles:
    - fedora.system_roles.kernel_settings
