---
- name: selectattr attr
  hosts: localhost
  gather_facts: false
  vars:
    bpftrace_users:
      - { user: metrics, sasluser: metrics, saslpassword: admin }
      - { user: foo }
      - { sasluser: bar }
  tasks:
    - set_fact:
        bpftrace_usernames: "{{ bpftrace_users | selectattr('user', 'defined') | map(attribute='user') | join(',') }}"
        foo: "{{ bpftrace_users | rejectattr('user', 'undefined') | list }}"
    - debug:
        msg: foo {{ foo | to_nice_json }} bpftrace_usernames {{ bpftrace_usernames | to_nice_json }}
