- hosts: localhost
  gather_facts: false
  tasks:
    - name: Investigate /etc/sysconfig/network presence
      tags:
        - 'tests::cleanup'
      stat:
        path: junk
      register: etc_sysconfig_network_stat
      ignore_errors: yes

    - command: ls nosuchfile
      register: __testme
      failed_when: false

    - debug:
        msg: here {{ __testme | to_nice_json }}
