- hosts: localhost
  tasks:
    - name: Investigate /etc/sysconfig/network presence
      tags:
        - 'tests::cleanup'
      stat:
        path: junk
      register: etc_sysconfig_network_stat
      ignore_errors: yes
