---
- name: set parameters for test
  hosts: localhost
  tasks:
  - set_fact:
      storage_pool_defaults:
        state: "present"
        type: lvm
        encryption: false
        encryption_passphrase: null
        encryption_key_file: null
        encryption_cipher: null
        encryption_key_size: null
        encryption_luks_version: null
        raid_level: null
      storage_volume_defaults:
        state: "present"
        type: lvm
        size: 0
        fs_type: "xfs"
        fs_label: ""
        fs_create_options: ""
        fs_overwrite_existing: true
        mount_point: ""
        mount_options: "defaults"
        mount_check: 0
        mount_passno: 0
        mount_device_identifier: "uuid"  # uuid|label|path
        raid_level: null
        raid_device_count: null
        raid_spare_count: null
        raid_chunk_size: null
        raid_metadata_version: null
        encryption: false
        encryption_passphrase: null
        encryption_key_file: null
        encryption_cipher: null
        encryption_key_size: null
        encryption_luks_version: null
      storage_pools:
      - name: foo
        disks:
          - a
          - b
        volumes:
          - name: test1
            size: 32
            mount_point: /test
      _storage_pools: []
      _storage_volumes: []  # list of standalone volumes w/ defaults applied as necessary
      _storage_vol_defaults: []  # list w/ volume default dict for each pool volume
      _storage_vols_no_defaults: []  # combined list of pool volumes w/o defaults applied
      _storage_vols_w_defaults: []  # combined list of volumes w/ defaults applied
      _storage_vol_pools: []  # combined list of pool name for each volume
      _storage_vols_no_defaults_by_pool: {}  # dict w/ pool name keys and pool volume list values

  - name: Apply defaults to pools and volumes [1/6]
    set_fact:
      _storage_pools: "{{ _storage_pools|default([]) }} + [ {{ storage_pool_defaults|combine(pool) }} ]"
    loop: "{{ storage_pools }}"
    loop_control:
      loop_var: pool
    when: storage_pools is defined

  - name: Apply defaults to pools and volumes [2/6]
    set_fact:
      _storage_vols_no_defaults: "{{ _storage_vols_no_defaults|default([]) }} + [{{ item.1 }}]"
      _storage_vol_defaults: "{{ _storage_vol_defaults|default([]) }} + [{{ storage_volume_defaults }}]"
      _storage_vol_pools: "{{ _storage_vol_pools|default([]) }} + ['{{ item.0.name }}']"
    loop: "{{ _storage_pools|subelements('volumes', skip_missing=true) }}"
    when: storage_pools is defined

  - name: Apply defaults to pools and volumes [3/6]
    set_fact:
      _storage_vols_w_defaults: "{{ _storage_vols_w_defaults|default([]) }} + [ {{ item.1|combine(item.0, {'pool': _storage_vol_pools[idx]}) }} ]"
    loop: "{{ _storage_vols_no_defaults|zip(_storage_vol_defaults)|list }}"
    loop_control:
      index_var: idx
    when: storage_pools is defined

  - name: Apply defaults to pools and volumes [4/6]
    set_fact:
      # json_query(...) used instead of "|selectattr('pool', 'equalto', item.name)|list"
      # as that expression wouldn't work with Jinja versions <2.8
      # 'sameas' works because python interns small strings
      _storage_vols_no_defaults_by_pool: |
        {% set vols = {} %}
        {% for pool in _storage_pools %}
        {%   for vol in _storage_vols_w_defaults %}
        {%     if vol.pool == pool.name %}
        {%       set _ = vols.__setitem__(pool.name, vol) %}
        {%     endif %}
        {%   endfor %}
        {% endfor %}
        {{ vols }}
      # _storage_vols_no_defaults_by_pool: "{{ _storage_vols_no_defaults_by_pool|default({})|
      #                                     combine({item.name: _storage_vols_w_defaults|selectattr('pool', 'sameas', item.name)|list}) }}"
      # _storage_vols_no_defaults_by_pool: "{{ _storage_vols_no_defaults_by_pool|default({})|
      #                                     combine({item.name: _storage_vols_w_defaults|json_query('[?pool==`\"{}\"`]'.format(item.name))}) }}"
    #loop: "{{ _storage_pools }}"
    when: storage_pools is defined

  - debug:
      msg: _storage_vols_no_defaults_by_pool is {{ _storage_vols_no_defaults_by_pool }}
