- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - debug:
        msg: "{{ number }}"
      loop:
        - one
        - two
      loop_control:
        loop_var: number
    - debug:
        msg: "{{ _number }}"
      loop:
        - one
        - two
      loop_control:
        loop_var: _number
