- name: begin handler_test subrole1
  debug:
    msg: first task in handler_test subrole1 {{ __myvar }}
  notify: calling handler
  changed_when: true

- name: include othertasks.yml from main role
  include_role:
    name: "{{ role_path ~ '/../../../' if role_path is defined else 'handler_test' }}"
    tasks_from: othertasks.yml
  vars:
    __calling_from: subrole1

- name: end handler_test subrole1
  debug:
    msg: last task in handler_test subrole1 {{ __myvar }}
  notify: calling handler
  changed_when: true
